SELECT * FROM source;
SELECT * FROM client;
SELECT * FROM sale;
SELECT * FROM good;
SELECT * FROM category;
SELECT * FROM sale_history;
SELECT * FROM status;
SELECT * FROM sale_has_good;
SELECT * FROM category_has_good;
